version: '3.9'

services:
  database:
    image: postgres:latest
    container_name: image-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: imageservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin759

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin759
    command: server --console-address ":9090" /data